ENV_FILE = 
TEAM_NAME = 
WORKSPACE_NAME = 
PROJECT_NAME = 
NEW_FULL_VIDEOS = 
ALL_FULL_VIDEOS = 
NEW_CROPPED_VIDEOS = 
ALL_CROPPED_VIDEOS = 
FRAME_RATE = 5
SELECTED_FRAMES = 
TEMP_JSON_FILE = 
ANNOTATED_FRAMES = 
FINAL_LABELS = 
PROJECT_YAML_FILE = 
IMAGES_GOOGLE_DRIVE_FOLDER_ID = 
LABELS_GOOGLE_DRIVE_FOLDER_ID = 
CROPS_GOOGLE_DRIVE_FOLDER_ID = 
VIDEOS_GOOGLE_DRIVE_FOLDER_ID = 

JSON_TEMPLATE = {
    "last_member_idx": 0,
    "datasets_for_annotation": []
}
